AWSTemplateFormatVersion: '2010-09-09'
Description: RDS (PostgreSQL) + ElastiCache (Redis) + S3 stack for production environment

Parameters:
  DBPassword:
    Type: String
    Description: Master password for the RDS PostgreSQL instance
    NoEcho: true
    MinLength: 8
    MaxLength: 41

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the RDS and Redis instances will be deployed

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for RDS (AZ1)

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet for RDS (AZ2)

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for Redis (AZ1)

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Private subnet for Redis (AZ2)

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group ID allowing access to RDS and Redis

Resources:

  # RDS Subnet Group: required for provisioning DB in specific subnets
  PrdDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS (PostgreSQL)
      SubnetIds:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      DBSubnetGroupName: prd-db-subnet-group

  # RDS PostgreSQL Instance
  PrdRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: prd-postgres-db
      AllocatedStorage: 20                         # 20 GiB of storage (free-tier eligible)
      DBInstanceClass: db.t3.micro                 # smallest burstable instance
      Engine: postgres
      EngineVersion: 17.5                          # must be valid in the given region
      MasterUsername: mydbuser
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref SecurityGroupId                     # externally injected SG with port 5432 open
      DBSubnetGroupName: !Ref PrdDBSubnetGroup
      PubliclyAccessible: true                     # allows public endpoint access (e.g. dev/test)
      BackupRetentionPeriod: 7
      MultiAZ: false
      StorageType: gp2

  # Redis Subnet Group: required for ElastiCache cluster
  PrdElastiCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for ElastiCache (Redis)
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      CacheSubnetGroupName: prd-redis-subnet-group

  # ElastiCache Redis Cluster
  PrdRedis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t2.micro                # free-tier eligible
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
        - !Ref SecurityGroupId                     # requires port 6379 open in SG
      CacheSubnetGroupName: !Ref PrdElastiCacheSubnetGroup

  # S3 Bucket for logs and backups
  PrdS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub prd-app-logs-${AWS::AccountId}-${AWS::Region}

Outputs:
  PrdRDS:
    Value: !Ref PrdRDSInstance
    Description: RDS PostgreSQL instance

  PrdRedis:
    Value: !Ref PrdRedis
    Description: ElastiCache Redis cluster

  PrdS3:
    Value: !Ref PrdS3Bucket
    Description: S3 bucket for application logs and backups
