apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml . | nindent 8 }}
{{- end }}

      # ====== initContainer 추가 ======
      initContainers:
        - name: sync-ssm
          image: amazon/aws-cli:2.15.9
          command: ["/bin/bash", "/scripts/sync-ssm-to-secret.sh"]
          volumeMounts:
            - name: sync-script
              mountPath: /scripts
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.aws.region | quote }}
      # ===============================

      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile | default "dev" | quote }}
            - name: AWS_REGION
              value: {{ .Values.aws.region | default "ap-northeast-2" | quote }}
            - name: SPRING_CLOUD_AWS_REGION_STATIC
              value: {{ .Values.aws.region | default "ap-northeast-2" | quote }}
            - name: LOGGING_LEVEL_IO_AWSPRING_CLOUD_PARAMSTORE
              value: DEBUG
          resources:
{{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: sync-script
          configMap:
            name: sync-ssm-script
            defaultMode: 0755
