AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Infrastructure - ECR(dev/prd) + GitHub OIDC IAM Role

Parameters:
  RepositoryName:
    Type: String
    Description: Base name of ECR Repository (e.g., infra-app-backend)

  GithubAccountId:
    Type: String
    Description: AWS Account ID for OIDC Trust Policy (12-digit number)

Resources:

  # dev용 ECR
  DevECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${RepositoryName}-dev"
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only last 3 dev images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: illsang-infra-dev
        - Key: ManagedBy
          Value: CloudFormation

  # prd용 ECR
  PrdECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${RepositoryName}-prd"
      ImageScanningConfiguration:
        scanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only last 3 prd images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: Project
          Value: illsang-infra-prd
        - Key: ManagedBy
          Value: CloudFormation

  # GitHub Actions → AWS Assume Role 허용용 OIDC Provider (최초 1회만 배포 요망)
  GitHubOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Tags:
        - Key: Name
          Value: github-oidc-provider

  # GitHub Actions에서 사용할 공통 IAM Role
  GitHubDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubDeployRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${GithubAccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:TeamFair/illsang-infra:* # fixme
      Policies:
        - PolicyName: ECRPushPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload
                Resource: "*"

Outputs:
  DevECRUri:
    Description: URI of the dev ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}-dev"

  PrdECRUri:
    Description: URI of the prd ECR repository
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RepositoryName}-prd"

  GitHubRoleArn:
    Description: IAM Role ARN for GitHub OIDC Deployments
    Value: !GetAtt GitHubDeployRole.Arn