# argocd-values.yaml

server:
  service:
    type: NodePort
    ports:
      http:
        nodePort: 30223
      https:
        nodePort: 32244
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists

controller:
  replicas: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists

repoServer:
  replicas: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists

applicationSet:
  enabled: false

notifications:
  enabled: false

dex:
  enabled: false

redis:
  enabled: false