# values.yaml
spring:
  profile: dev

replicaCount: 1

image:
  repository: "" # 외부에서 입력
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: backend.matq.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

imagePullSecrets:
  - name: ecr-creds

namespaceOverride: ""