name: Build and Push to ECR(PRD)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repository
        uses: actions/checkout@v4

      - name: Checkout illsang-backend repository
        uses: actions/checkout@v4
        with:
          repository: TeamFair/illsang-backend
          ref: feat-LayerHex
          token: ${{ secrets.GITHUB_TOKEN }}
          path: app-source

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployRole
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          cd app-source
          FULL_REPO="$ECR_REGISTRY/${ECR_REPOSITORY}-prd"
          docker build -f module-bootstrap/Dockerfile -t $FULL_REPO:$IMAGE_TAG .
          docker push $FULL_REPO:$IMAGE_TAG

#      - name: Deploy to EC2 via SSH and restart K8s deployment
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ec2-user
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            echo ">>> Restarting Kubernetes Deployment"
#            kubectl rollout restart deployment app -n default
#            echo ">>> Waiting for rollout completion"
#            kubectl rollout status deployment app -n default --timeout=60s